"""Add audit_logs table

Revision ID: 68935b45d637
Revises: d056ac187ce9
Create Date: 2025-11-04 11:35:16.493498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68935b45d637'
down_revision: Union[str, Sequence[str], None] = 'd056ac187ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('description', sa.String(), nullable=True))
    op.create_index('idx_audit_entity', 'audit_logs', ['entity'], unique=False)
    op.create_index('idx_audit_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('idx_audit_performed_by', 'audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['performed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_performed_by', table_name='audit_logs')
    op.drop_index('idx_audit_entity_id', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###
