"""Add audit_logs table2

Revision ID: cca85363d632
Revises: 68935b45d637
Create Date: 2025-11-04 11:39:30.525801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca85363d632'
down_revision: Union[str, Sequence[str], None] = '68935b45d637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_entity_id', table_name='audit_logs')
    op.drop_index('idx_audit_performed_by', table_name='audit_logs')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_index('idx_audit_performed_by', 'audit_logs', ['performed_by'], unique=False)
    op.create_index('idx_audit_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity'], unique=False)
    # ### end Alembic commands ###
