"""Add request_logs table

Revision ID: d056ac187ce9
Revises: 97fafdc51bb9
Create Date: 2025-11-04 10:16:11.658269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd056ac187ce9'
down_revision: Union[str, Sequence[str], None] = '97fafdc51bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('url', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('latency', sa.Float(), nullable=True))
    op.add_column('request_logs', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('message', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('response_body', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('error_trace', sa.String(), nullable=True))
    op.alter_column('request_logs', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_logs', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'request_logs', 'users', ['user_id'], ['id'])
    op.drop_column('request_logs', 'latency_ms')
    op.drop_column('request_logs', 'ip')
    op.drop_column('request_logs', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('request_logs', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('request_logs', sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'request_logs', type_='foreignkey')
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.alter_column('request_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('request_logs', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('request_logs', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('request_logs', 'error_trace')
    op.drop_column('request_logs', 'response_body')
    op.drop_column('request_logs', 'message')
    op.drop_column('request_logs', 'user_agent')
    op.drop_column('request_logs', 'latency')
    op.drop_column('request_logs', 'ip_address')
    op.drop_column('request_logs', 'url')
    # ### end Alembic commands ###
